-- EterDB demo: a small e-commerce schema (the kind an AI app-builder emits).
-- Used by `eter demo up`. The pgvector embedding column on products is added
-- separately by the demo loader *only when pgvector is available*, so the demo
-- runs on any Postgres while still exercising the extension-compatibility claim
-- where the extension is installed.
--
-- Tables are explicitly created in `public` so they never collide with the
-- `eter` engine schema (e.g. when the connecting role is itself named
-- "eter", which would otherwise route unqualified CREATEs via search_path).
CREATE SCHEMA IF NOT EXISTS public;
DROP TABLE IF EXISTS public.invoices, public.orders, public.products, public.customers CASCADE;

CREATE TABLE public.customers (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  email       text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.products (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  price_cents integer NOT NULL
  -- embedding vector(3) added by the demo loader when pgvector is present
);

CREATE TABLE public.orders (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id),
  status      text NOT NULL DEFAULT 'placed',
  total_cents integer NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.invoices (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    bigint NOT NULL REFERENCES public.orders(id),
  amount_cents integer NOT NULL,
  status      text NOT NULL DEFAULT 'issued',
  -- Foreign key into an external system (Stripe). The 2:00 PM incident corrupts
  -- amount_cents but these charges already fired, EterDB surfaces them as the
  -- non-reversible external effects (Case 3 / Act 2 seed) without pretending to undo them.
  stripe_charge_id text,
  issued_at   timestamptz NOT NULL DEFAULT now()
);
